version: '3.9'

services:
  web:
    build: ./web
    ports:
      - 3100:3000
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_WS_URL=ws://localhost:8502/predict

  api:
    build: ./api
    ports:
      - 8502:8502
    volumes:
      - ./api:/api
    stdin_open: true
    tty: true
    command: uvicorn index:app --host 0.0.0.0 --port 8502 --reload

volumes:
  web_node_modules: