FROM node:20 AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci --only=production

COPY .next ./.next
COPY public ./public

CMD ["npm", "run", "start"]
